---
name: HelmChartValuesBuilder

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo contents
        uses: actions/checkout@v2

      - name: execute shell script
        run: ./tools/create-helm-config-files.sh

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updating Value Files for Helm Charts" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 